"""Type stubs for the Rust extension module (tidytrail-core via PyO3)."""

from typing import List, Tuple

__version__: str
MAX_DEPTH: int
MAX_PATHS_PER_REQUEST: int
AUDIT_LOG_DIR_ENV: str
AUDIT_LOG_FILE_NAME: str

class Node:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def category(self) -> str: ...
    @property
    def children(self) -> List[Node]: ...
    def __len__(self) -> int: ...

class ScanIssue:
    @property
    def path(self) -> str: ...
    @property
    def message(self) -> str: ...

class ScanResult:
    @property
    def root(self) -> Node: ...
    @property
    def issues(self) -> List[ScanIssue]: ...

class TrashReport:
    @property
    def trashed(self) -> List[str]: ...
    @property
    def failed(self) -> List[Tuple[str, str]]: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def audit_log(self) -> str: ...
    @property
    def ok(self) -> bool: ...

class Cleaner:
    def __new__(cls, scan_root: str, audit_log_dir: str) -> Cleaner: ...
    @property
    def scan_root(self) -> str: ...
    @property
    def audit_log(self) -> str: ...
    def check(self, path: str) -> str: ...
    def trash(self, paths: List[str], *, dry_run: bool = False) -> TrashReport: ...

def scan(path: str) -> ScanResult: ...
def format_bytes(size: int) -> str: ...
